# Настройки сервера
server:
  port: 8080

app:
  max-messages: 10
  file-content-load:
    enabled: false

# Настройки базы данных PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  # Настройки JPA
  jpa:
    # hibernate:
      # ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Настройки Liquibase
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
    enabled: true

  # Настройки Spring AI Ollama
  ai:
    ollama:
      base-url: http://localhost:11431
      chat:
        model: gemma3:4b-it-qat
      embedding:
        model: mxbai-embed-large:335m

# Настройки логирования
logging:
  level:
    com.example.springaiapp: DEBUG
    org.springframework.ai: info
    org.springframework.ai.chat.client.advisor: debug
